# Lab Docker Compose
version: '3.8'

services:
  database1:
    env_file: .env
    build: ../mysql
    restart: always 
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password


#Wordpress
#  wordpress:
#    build: ./wordpress
#    restart: unless-stopped
#    env_file: .env
#    environment:
#      - WORDPRESS_DB_HOST=db:3306
#      - WORDPRESS_DB_USER=$MYSQL_USER
#      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
#      - WORDPRESS_DB_NAME=wordpress
#    volumes:
#      - wordpress:/var/www/html

#Webserver
#  webserver:
#    depends_on:
#      - wordpress
#    image: nginx:1.15.12-alpine
#    container_name: webserver
#    restart: unless-stopped
#    ports:
#      - "8080:80"
#    volumes:
#      - wordpress:/var/www/html
#      - ./nginx-conf:/etc/nginx/conf.d
    
#Volumes
volumes:
  wordpress:
  dbdata: